facebook_controller:
    resource: "@IcapOAuthBundle/Controller/FacebookController.php"
    type: annotation
    prefix: /


hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /login/hwi

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix: /connect

facebook_login:
    pattern: /login/check_facebook
